//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicTaggingLight.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicTaggingLight.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;items&gt;
        ///  &lt;item Key=&quot;AlbumCover&quot; Value=&quot;0&quot;/&gt;
        ///  &lt;item Key=&quot;Title&quot; Value=&quot;1&quot;/&gt;
        ///  &lt;item Key=&quot;Artist&quot; Value=&quot;2&quot;/&gt;
        ///  &lt;item Key=&quot;Album&quot; Value=&quot;3&quot;/&gt;
        ///  &lt;item Key=&quot;Track&quot; Value=&quot;4&quot;/&gt;
        ///  &lt;item Key=&quot;Year&quot; Value=&quot;5&quot;/&gt;
        ///  &lt;item Key=&quot;Genre&quot; Value=&quot;6&quot;/&gt;
        ///  &lt;item Key=&quot;FileName&quot; Value=&quot;7&quot;/&gt;
        ///  &lt;item Key=&quot;FilePath&quot; Value=&quot;8&quot;/&gt;
        ///  &lt;item Key=&quot;Comment&quot; Value=&quot;9&quot;/&gt;
        ///&lt;/items&gt;
        ///.
        /// </summary>
        internal static string colsorder {
            get {
                return ResourceManager.GetString("colsorder", resourceCulture);
            }
        }
    }
}
